# Generated by Django 3.2.6 on 2021-08-10 14:09

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user/teacher/')),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.PositiveIntegerField()),
                ('notify_me', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', user.models.UserManager()),
            ],
        ),
    ]
