# Generated by Django 3.2.6 on 2021-08-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210810_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rejected_once',
            field=models.BooleanField(default=False),
        ),
    ]
