# Generated by Django 3.2.6 on 2021-08-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='want_as_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
