# Generated by Django 3.2.6 on 2021-08-12 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_want_as_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='want_as_teacher',
            new_name='request_as_teacher',
        ),
    ]
