# Generated by Django 3.2.6 on 2021-08-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_of_post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
